package com.google.android.gms.internal.mlkit_vision_text;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;
/* loaded from: classes2.dex */
final class zzfw implements ObjectEncoder<zziv> {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzfw zza = new zzfw();
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzcm zzcmVar = new zzcm();
        zzcmVar.zza(1);
        zzb = builder.withProperty(zzcmVar.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzcm zzcmVar2 = new zzcm();
        zzcmVar2.zza(2);
        zzc = builder2.withProperty(zzcmVar2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzcm zzcmVar3 = new zzcm();
        zzcmVar3.zza(37);
        zzd = builder3.withProperty(zzcmVar3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzcm zzcmVar4 = new zzcm();
        zzcmVar4.zza(3);
        zze = builder4.withProperty(zzcmVar4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzcm zzcmVar5 = new zzcm();
        zzcmVar5.zza(20);
        zzf = builder5.withProperty(zzcmVar5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzcm zzcmVar6 = new zzcm();
        zzcmVar6.zza(4);
        zzg = builder6.withProperty(zzcmVar6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzcm zzcmVar7 = new zzcm();
        zzcmVar7.zza(29);
        zzh = builder7.withProperty(zzcmVar7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzcm zzcmVar8 = new zzcm();
        zzcmVar8.zza(5);
        zzi = builder8.withProperty(zzcmVar8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzcm zzcmVar9 = new zzcm();
        zzcmVar9.zza(59);
        zzj = builder9.withProperty(zzcmVar9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzcm zzcmVar10 = new zzcm();
        zzcmVar10.zza(6);
        zzk = builder10.withProperty(zzcmVar10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzcm zzcmVar11 = new zzcm();
        zzcmVar11.zza(7);
        zzl = builder11.withProperty(zzcmVar11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzcm zzcmVar12 = new zzcm();
        zzcmVar12.zza(58);
        zzm = builder12.withProperty(zzcmVar12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzcm zzcmVar13 = new zzcm();
        zzcmVar13.zza(48);
        zzn = builder13.withProperty(zzcmVar13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzcm zzcmVar14 = new zzcm();
        zzcmVar14.zza(49);
        zzo = builder14.withProperty(zzcmVar14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzcm zzcmVar15 = new zzcm();
        zzcmVar15.zza(18);
        zzp = builder15.withProperty(zzcmVar15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzcm zzcmVar16 = new zzcm();
        zzcmVar16.zza(26);
        zzq = builder16.withProperty(zzcmVar16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzcm zzcmVar17 = new zzcm();
        zzcmVar17.zza(27);
        zzr = builder17.withProperty(zzcmVar17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzcm zzcmVar18 = new zzcm();
        zzcmVar18.zza(28);
        zzs = builder18.withProperty(zzcmVar18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzcm zzcmVar19 = new zzcm();
        zzcmVar19.zza(44);
        zzt = builder19.withProperty(zzcmVar19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzcm zzcmVar20 = new zzcm();
        zzcmVar20.zza(45);
        zzu = builder20.withProperty(zzcmVar20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzcm zzcmVar21 = new zzcm();
        zzcmVar21.zza(19);
        zzv = builder21.withProperty(zzcmVar21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzcm zzcmVar22 = new zzcm();
        zzcmVar22.zza(21);
        zzw = builder22.withProperty(zzcmVar22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzcm zzcmVar23 = new zzcm();
        zzcmVar23.zza(22);
        zzx = builder23.withProperty(zzcmVar23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzcm zzcmVar24 = new zzcm();
        zzcmVar24.zza(8);
        zzy = builder24.withProperty(zzcmVar24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzcm zzcmVar25 = new zzcm();
        zzcmVar25.zza(9);
        zzz = builder25.withProperty(zzcmVar25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzcm zzcmVar26 = new zzcm();
        zzcmVar26.zza(10);
        zzA = builder26.withProperty(zzcmVar26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzcm zzcmVar27 = new zzcm();
        zzcmVar27.zza(11);
        zzB = builder27.withProperty(zzcmVar27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzcm zzcmVar28 = new zzcm();
        zzcmVar28.zza(12);
        zzC = builder28.withProperty(zzcmVar28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzcm zzcmVar29 = new zzcm();
        zzcmVar29.zza(13);
        zzD = builder29.withProperty(zzcmVar29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzcm zzcmVar30 = new zzcm();
        zzcmVar30.zza(14);
        zzE = builder30.withProperty(zzcmVar30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzcm zzcmVar31 = new zzcm();
        zzcmVar31.zza(15);
        zzF = builder31.withProperty(zzcmVar31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzcm zzcmVar32 = new zzcm();
        zzcmVar32.zza(16);
        zzG = builder32.withProperty(zzcmVar32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzcm zzcmVar33 = new zzcm();
        zzcmVar33.zza(17);
        zzH = builder33.withProperty(zzcmVar33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzcm zzcmVar34 = new zzcm();
        zzcmVar34.zza(23);
        zzI = builder34.withProperty(zzcmVar34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzcm zzcmVar35 = new zzcm();
        zzcmVar35.zza(24);
        zzJ = builder35.withProperty(zzcmVar35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzcm zzcmVar36 = new zzcm();
        zzcmVar36.zza(25);
        zzK = builder36.withProperty(zzcmVar36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzcm zzcmVar37 = new zzcm();
        zzcmVar37.zza(39);
        zzL = builder37.withProperty(zzcmVar37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("deleteModelLogEvent");
        zzcm zzcmVar38 = new zzcm();
        zzcmVar38.zza(40);
        zzM = builder38.withProperty(zzcmVar38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzcm zzcmVar39 = new zzcm();
        zzcmVar39.zza(30);
        zzN = builder39.withProperty(zzcmVar39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzcm zzcmVar40 = new zzcm();
        zzcmVar40.zza(31);
        zzO = builder40.withProperty(zzcmVar40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzcm zzcmVar41 = new zzcm();
        zzcmVar41.zza(32);
        zzP = builder41.withProperty(zzcmVar41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzcm zzcmVar42 = new zzcm();
        zzcmVar42.zza(33);
        zzQ = builder42.withProperty(zzcmVar42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzcm zzcmVar43 = new zzcm();
        zzcmVar43.zza(34);
        zzR = builder43.withProperty(zzcmVar43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzcm zzcmVar44 = new zzcm();
        zzcmVar44.zza(35);
        zzS = builder44.withProperty(zzcmVar44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzcm zzcmVar45 = new zzcm();
        zzcmVar45.zza(36);
        zzT = builder45.withProperty(zzcmVar45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzcm zzcmVar46 = new zzcm();
        zzcmVar46.zza(46);
        zzU = builder46.withProperty(zzcmVar46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzcm zzcmVar47 = new zzcm();
        zzcmVar47.zza(47);
        zzV = builder47.withProperty(zzcmVar47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzcm zzcmVar48 = new zzcm();
        zzcmVar48.zza(42);
        zzW = builder48.withProperty(zzcmVar48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzcm zzcmVar49 = new zzcm();
        zzcmVar49.zza(50);
        zzX = builder49.withProperty(zzcmVar49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("leakedHandleEvent");
        zzcm zzcmVar50 = new zzcm();
        zzcmVar50.zza(51);
        zzY = builder50.withProperty(zzcmVar50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzcm zzcmVar51 = new zzcm();
        zzcmVar51.zza(52);
        zzZ = builder51.withProperty(zzcmVar51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzcm zzcmVar52 = new zzcm();
        zzcmVar52.zza(53);
        zzaa = builder52.withProperty(zzcmVar52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzcm zzcmVar53 = new zzcm();
        zzcmVar53.zza(54);
        zzab = builder53.withProperty(zzcmVar53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzcm zzcmVar54 = new zzcm();
        zzcmVar54.zza(60);
        zzac = builder54.withProperty(zzcmVar54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzcm zzcmVar55 = new zzcm();
        zzcmVar55.zza(55);
        zzad = builder55.withProperty(zzcmVar55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzcm zzcmVar56 = new zzcm();
        zzcmVar56.zza(56);
        zzae = builder56.withProperty(zzcmVar56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzcm zzcmVar57 = new zzcm();
        zzcmVar57.zza(57);
        zzaf = builder57.withProperty(zzcmVar57.zzb()).build();
    }

    private zzfw() {
    }

    @Override // com.google.firebase.encoders.ObjectEncoder, com.google.firebase.encoders.Encoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, ObjectEncoderContext objectEncoderContext) throws IOException {
        zziv zzivVar = (zziv) obj;
        ObjectEncoderContext objectEncoderContext2 = objectEncoderContext;
        objectEncoderContext2.add(zzb, zzivVar.zzd());
        objectEncoderContext2.add(zzc, zzivVar.zzb());
        objectEncoderContext2.add(zzd, zzivVar.zze());
        objectEncoderContext2.add(zze, (Object) null);
        objectEncoderContext2.add(zzf, (Object) null);
        objectEncoderContext2.add(zzg, (Object) null);
        objectEncoderContext2.add(zzh, (Object) null);
        objectEncoderContext2.add(zzi, (Object) null);
        objectEncoderContext2.add(zzj, (Object) null);
        objectEncoderContext2.add(zzk, zzivVar.zzc());
        objectEncoderContext2.add(zzl, (Object) null);
        objectEncoderContext2.add(zzm, (Object) null);
        objectEncoderContext2.add(zzn, (Object) null);
        objectEncoderContext2.add(zzo, (Object) null);
        objectEncoderContext2.add(zzp, (Object) null);
        objectEncoderContext2.add(zzq, (Object) null);
        objectEncoderContext2.add(zzr, (Object) null);
        objectEncoderContext2.add(zzs, (Object) null);
        objectEncoderContext2.add(zzt, (Object) null);
        objectEncoderContext2.add(zzu, (Object) null);
        objectEncoderContext2.add(zzv, (Object) null);
        objectEncoderContext2.add(zzw, (Object) null);
        objectEncoderContext2.add(zzx, (Object) null);
        objectEncoderContext2.add(zzy, (Object) null);
        objectEncoderContext2.add(zzz, (Object) null);
        objectEncoderContext2.add(zzA, (Object) null);
        objectEncoderContext2.add(zzB, (Object) null);
        objectEncoderContext2.add(zzC, (Object) null);
        objectEncoderContext2.add(zzD, (Object) null);
        objectEncoderContext2.add(zzE, (Object) null);
        objectEncoderContext2.add(zzF, (Object) null);
        objectEncoderContext2.add(zzG, (Object) null);
        objectEncoderContext2.add(zzH, (Object) null);
        objectEncoderContext2.add(zzI, (Object) null);
        objectEncoderContext2.add(zzJ, (Object) null);
        objectEncoderContext2.add(zzK, (Object) null);
        objectEncoderContext2.add(zzL, (Object) null);
        objectEncoderContext2.add(zzM, (Object) null);
        objectEncoderContext2.add(zzN, (Object) null);
        objectEncoderContext2.add(zzO, (Object) null);
        objectEncoderContext2.add(zzP, (Object) null);
        objectEncoderContext2.add(zzQ, (Object) null);
        objectEncoderContext2.add(zzR, (Object) null);
        objectEncoderContext2.add(zzS, (Object) null);
        objectEncoderContext2.add(zzT, zzivVar.zza());
        objectEncoderContext2.add(zzU, (Object) null);
        objectEncoderContext2.add(zzV, (Object) null);
        objectEncoderContext2.add(zzW, (Object) null);
        objectEncoderContext2.add(zzX, (Object) null);
        objectEncoderContext2.add(zzY, (Object) null);
        objectEncoderContext2.add(zzZ, (Object) null);
        objectEncoderContext2.add(zzaa, (Object) null);
        objectEncoderContext2.add(zzab, (Object) null);
        objectEncoderContext2.add(zzac, (Object) null);
        objectEncoderContext2.add(zzad, (Object) null);
        objectEncoderContext2.add(zzae, (Object) null);
        objectEncoderContext2.add(zzaf, (Object) null);
    }
}
