package com.google.android.gms.internal.mlkit_vision_common;

import com.google.firebase.encoders.config.Configurator;
import com.google.firebase.encoders.config.EncoderConfig;
/* loaded from: classes2.dex */
public final class zzfo implements Configurator {
    public static final Configurator zza = new zzfo();

    private zzfo() {
    }

    @Override // com.google.firebase.encoders.config.Configurator
    public final void configure(EncoderConfig encoderConfig) {
        encoderConfig.registerEncoder(zzhc.class, zzdr.zza);
        encoderConfig.registerEncoder(zzin.class, zzfg.zza);
        encoderConfig.registerEncoder(zzhd.class, zzds.zza);
        encoderConfig.registerEncoder(zzhg.class, zzdu.zza);
        encoderConfig.registerEncoder(zzhe.class, zzdt.zza);
        encoderConfig.registerEncoder(zzhf.class, zzdv.zza);
        encoderConfig.registerEncoder(zzgi.class, zzda.zza);
        encoderConfig.registerEncoder(zzgh.class, zzcz.zza);
        encoderConfig.registerEncoder(zzgq.class, zzdk.zza);
        encoderConfig.registerEncoder(zzij.class, zzfa.zza);
        encoderConfig.registerEncoder(zzgg.class, zzcy.zza);
        encoderConfig.registerEncoder(zzgf.class, zzcx.zza);
        encoderConfig.registerEncoder(zzhm.class, zzed.zza);
        encoderConfig.registerEncoder(zzjf.class, zzdg.zza);
        encoderConfig.registerEncoder(zzgo.class, zzdi.zza);
        encoderConfig.registerEncoder(zzgm.class, zzdf.zza);
        encoderConfig.registerEncoder(zzhn.class, zzee.zza);
        encoderConfig.registerEncoder(zzig.class, zzex.zza);
        encoderConfig.registerEncoder(zzih.class, zzey.zza);
        encoderConfig.registerEncoder(zzhk.class, zzeb.zza);
        encoderConfig.registerEncoder(zzje.class, zzch.zza);
        encoderConfig.registerEncoder(zzhl.class, zzec.zza);
        encoderConfig.registerEncoder(zzho.class, zzef.zza);
        encoderConfig.registerEncoder(zzhr.class, zzei.zza);
        encoderConfig.registerEncoder(zzhq.class, zzeh.zza);
        encoderConfig.registerEncoder(zzhp.class, zzeg.zza);
        encoderConfig.registerEncoder(zzhw.class, zzen.zza);
        encoderConfig.registerEncoder(zzhx.class, zzeo.zza);
        encoderConfig.registerEncoder(zzhz.class, zzeq.zza);
        encoderConfig.registerEncoder(zzhy.class, zzep.zza);
        encoderConfig.registerEncoder(zzhj.class, zzea.zza);
        encoderConfig.registerEncoder(zzia.class, zzer.zza);
        encoderConfig.registerEncoder(zzib.class, zzes.zza);
        encoderConfig.registerEncoder(zzic.class, zzet.zza);
        encoderConfig.registerEncoder(zzid.class, zzeu.zza);
        encoderConfig.registerEncoder(zzif.class, zzev.zza);
        encoderConfig.registerEncoder(zzie.class, zzew.zza);
        encoderConfig.registerEncoder(zzhv.class, zzej.zza);
        encoderConfig.registerEncoder(zzgx.class, zzdp.zza);
        encoderConfig.registerEncoder(zzht.class, zzel.zza);
        encoderConfig.registerEncoder(zzhs.class, zzek.zza);
        encoderConfig.registerEncoder(zzhu.class, zzem.zza);
        encoderConfig.registerEncoder(zzii.class, zzez.zza);
        encoderConfig.registerEncoder(zzir.class, zzfk.zza);
        encoderConfig.registerEncoder(zzfu.class, zzcm.zza);
        encoderConfig.registerEncoder(zzfs.class, zzck.zza);
        encoderConfig.registerEncoder(zzfr.class, zzcj.zza);
        encoderConfig.registerEncoder(zzft.class, zzcl.zza);
        encoderConfig.registerEncoder(zzfw.class, zzco.zza);
        encoderConfig.registerEncoder(zzfv.class, zzcn.zza);
        encoderConfig.registerEncoder(zzfx.class, zzcp.zza);
        encoderConfig.registerEncoder(zzfy.class, zzcq.zza);
        encoderConfig.registerEncoder(zzfz.class, zzcr.zza);
        encoderConfig.registerEncoder(zzga.class, zzcs.zza);
        encoderConfig.registerEncoder(zzgb.class, zzct.zza);
        encoderConfig.registerEncoder(zzbh.class, zzcd.zza);
        encoderConfig.registerEncoder(zzbj.class, zzcf.zza);
        encoderConfig.registerEncoder(zzbi.class, zzce.zza);
        encoderConfig.registerEncoder(zzgv.class, zzdn.zza);
        encoderConfig.registerEncoder(zzgj.class, zzdb.zza);
        encoderConfig.registerEncoder(zzaq.class, zzbl.zza);
        encoderConfig.registerEncoder(zzap.class, zzbm.zza);
        encoderConfig.registerEncoder(zzgk.class, zzdd.zza);
        encoderConfig.registerEncoder(zzas.class, zzbn.zza);
        encoderConfig.registerEncoder(zzar.class, zzbo.zza);
        encoderConfig.registerEncoder(zzaw.class, zzbr.zza);
        encoderConfig.registerEncoder(zzav.class, zzbs.zza);
        encoderConfig.registerEncoder(zzau.class, zzbp.zza);
        encoderConfig.registerEncoder(zzat.class, zzbq.zza);
        encoderConfig.registerEncoder(zzay.class, zzbt.zza);
        encoderConfig.registerEncoder(zzax.class, zzbu.zza);
        encoderConfig.registerEncoder(zzba.class, zzbv.zza);
        encoderConfig.registerEncoder(zzaz.class, zzbw.zza);
        encoderConfig.registerEncoder(zzbg.class, zzcb.zza);
        encoderConfig.registerEncoder(zzbf.class, zzcc.zza);
        encoderConfig.registerEncoder(zzbc.class, zzbx.zza);
        encoderConfig.registerEncoder(zzbb.class, zzby.zza);
        encoderConfig.registerEncoder(zzbe.class, zzbz.zza);
        encoderConfig.registerEncoder(zzbd.class, zzca.zza);
        encoderConfig.registerEncoder(zziz.class, zzfd.zza);
        encoderConfig.registerEncoder(zzis.class, zzdc.zza);
        encoderConfig.registerEncoder(zziw.class, zzdz.zza);
        encoderConfig.registerEncoder(zziv.class, zzdy.zza);
        encoderConfig.registerEncoder(zzit.class, zzdh.zza);
        encoderConfig.registerEncoder(zziy.class, zzfc.zza);
        encoderConfig.registerEncoder(zzix.class, zzfb.zza);
        encoderConfig.registerEncoder(zzja.class, zzfe.zza);
        encoderConfig.registerEncoder(zziu.class, zzdl.zza);
        encoderConfig.registerEncoder(zzjd.class, zzfm.zza);
        encoderConfig.registerEncoder(zzjc.class, zzfn.zza);
        encoderConfig.registerEncoder(zzjb.class, zzfl.zza);
        encoderConfig.registerEncoder(zzik.class, zzff.zza);
        encoderConfig.registerEncoder(zzgu.class, zzdm.zza);
        encoderConfig.registerEncoder(zzgy.class, zzdq.zza);
        encoderConfig.registerEncoder(zzfq.class, zzci.zza);
        encoderConfig.registerEncoder(zzgp.class, zzdj.zza);
        encoderConfig.registerEncoder(zzgw.class, zzdo.zza);
        encoderConfig.registerEncoder(zzgl.class, zzde.zza);
        encoderConfig.registerEncoder(zzhi.class, zzdx.zza);
        encoderConfig.registerEncoder(zzhh.class, zzdw.zza);
        encoderConfig.registerEncoder(zzao.class, zzbk.zza);
        encoderConfig.registerEncoder(zzio.class, zzfh.zza);
        encoderConfig.registerEncoder(zziq.class, zzfj.zza);
        encoderConfig.registerEncoder(zzip.class, zzfi.zza);
        encoderConfig.registerEncoder(zzfp.class, zzcg.zza);
        encoderConfig.registerEncoder(zzge.class, zzcw.zza);
        encoderConfig.registerEncoder(zzgd.class, zzcv.zza);
        encoderConfig.registerEncoder(zzgc.class, zzcu.zza);
    }
}
