package atd.az;

import androidx.exifinterface.media.ExifInterface;
import atd.at.o;
/* loaded from: classes.dex */
public interface g {
    public static final o A;
    public static final o B;
    public static final o C;
    public static final o D;
    public static final o E;
    public static final o F;
    public static final o G;
    public static final o H;
    public static final o I;
    public static final o J;
    public static final o K;
    public static final o L;
    public static final o M;
    public static final o N;
    public static final o O;
    public static final o P;
    public static final o Q;
    public static final o R;
    public static final o S;
    public static final o T;
    public static final o U;
    public static final o V;
    public static final o W;
    public static final o X;
    public static final o Y;
    public static final o Z;

    /* renamed from: a  reason: collision with root package name */
    public static final o f12245a;
    public static final o aa;
    public static final o ab;
    public static final o ac;
    public static final o ad;
    public static final o ae;
    public static final o af;
    public static final o ag;
    public static final o ah;
    public static final o ai;
    public static final o aj;
    public static final o ak;
    public static final o al;
    public static final o am;
    public static final o an;
    public static final o ao;
    public static final o b;
    public static final o c;

    /* renamed from: d  reason: collision with root package name */
    public static final o f12246d;
    public static final o e;
    public static final o f;
    public static final o g;
    public static final o h;
    public static final o i;
    public static final o j;
    public static final o k;
    public static final o l;
    public static final o m;
    public static final o n;
    public static final o o;
    public static final o p;
    public static final o q;
    public static final o r;
    public static final o s;
    public static final o t;
    public static final o u;
    public static final o v;
    public static final o w;
    public static final o x;
    public static final o y;
    public static final o z;

    static {
        o oVar = new o("1.2.840.10045");
        f12245a = oVar;
        o b2 = oVar.b("1");
        b = b2;
        c = b2.b("1");
        o b3 = b2.b(ExifInterface.GPS_MEASUREMENT_2D);
        f12246d = b3;
        e = b3.b("3.1");
        f = b3.b("3.2");
        g = b3.b("3.3");
        o b4 = oVar.b("4");
        h = b4;
        i = b4.b("1");
        o b5 = oVar.b(ExifInterface.GPS_MEASUREMENT_2D);
        j = b5;
        k = b5.b("1");
        o b6 = b4.b(ExifInterface.GPS_MEASUREMENT_3D);
        l = b6;
        m = b6.b("1");
        n = b6.b(ExifInterface.GPS_MEASUREMENT_2D);
        o = b6.b(ExifInterface.GPS_MEASUREMENT_3D);
        p = b6.b("4");
        o b7 = oVar.b(ExifInterface.GPS_MEASUREMENT_3D);
        q = b7;
        o b8 = b7.b("0");
        r = b8;
        s = b8.b("1");
        t = b8.b(ExifInterface.GPS_MEASUREMENT_2D);
        u = b8.b(ExifInterface.GPS_MEASUREMENT_3D);
        v = b8.b("4");
        w = b8.b("5");
        x = b8.b("6");
        y = b8.b("7");
        z = b8.b("8");
        A = b8.b("9");
        B = b8.b("10");
        C = b8.b("11");
        D = b8.b("12");
        E = b8.b("13");
        F = b8.b("14");
        G = b8.b("15");
        H = b8.b("16");
        I = b8.b("17");
        J = b8.b("18");
        K = b8.b("19");
        L = b8.b("20");
        o b9 = b7.b("1");
        M = b9;
        N = b9.b("1");
        O = b9.b(ExifInterface.GPS_MEASUREMENT_2D);
        P = b9.b(ExifInterface.GPS_MEASUREMENT_3D);
        Q = b9.b("4");
        R = b9.b("5");
        S = b9.b("6");
        T = b9.b("7");
        U = new o("1.2.840.10040.4.1");
        V = new o("1.2.840.10040.4.3");
        o oVar2 = new o("1.3.133.16.840.63.0");
        W = oVar2;
        X = oVar2.b(ExifInterface.GPS_MEASUREMENT_2D);
        Y = oVar2.b(ExifInterface.GPS_MEASUREMENT_3D);
        Z = oVar2.b("16");
        o oVar3 = new o("1.2.840.10046");
        aa = oVar3;
        ab = oVar3.b("2.1");
        o b10 = oVar3.b(ExifInterface.GPS_MEASUREMENT_3D);
        ac = b10;
        ad = b10.b("1");
        ae = b10.b(ExifInterface.GPS_MEASUREMENT_2D);
        af = b10.b(ExifInterface.GPS_MEASUREMENT_3D);
        ag = b10.b("4");
        ah = b10.b("5");
        ai = b10.b("6");
        aj = b10.b("7");
        ak = b10.b("8");
        o oVar4 = new o("1.3.133.16.840.9.44");
        al = oVar4;
        o b11 = oVar4.b("1");
        am = b11;
        an = b11.b("1");
        ao = b11.b(ExifInterface.GPS_MEASUREMENT_2D);
    }
}
