package com.google.android.gms.internal.mlkit_vision_face;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;
/* loaded from: classes2.dex */
final class zzgi implements ObjectEncoder {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzgi zza = new zzgi();
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzag;
    private static final FieldDescriptor zzah;
    private static final FieldDescriptor zzai;
    private static final FieldDescriptor zzaj;
    private static final FieldDescriptor zzak;
    private static final FieldDescriptor zzal;
    private static final FieldDescriptor zzam;
    private static final FieldDescriptor zzan;
    private static final FieldDescriptor zzao;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzcq zzcqVar = new zzcq();
        zzcqVar.zza(1);
        zzb = builder.withProperty(zzcqVar.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzcq zzcqVar2 = new zzcq();
        zzcqVar2.zza(2);
        zzc = builder2.withProperty(zzcqVar2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzcq zzcqVar3 = new zzcq();
        zzcqVar3.zza(37);
        zzd = builder3.withProperty(zzcqVar3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("clientType");
        zzcq zzcqVar4 = new zzcq();
        zzcqVar4.zza(61);
        zze = builder4.withProperty(zzcqVar4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzcq zzcqVar5 = new zzcq();
        zzcqVar5.zza(3);
        zzf = builder5.withProperty(zzcqVar5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzcq zzcqVar6 = new zzcq();
        zzcqVar6.zza(20);
        zzg = builder6.withProperty(zzcqVar6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzcq zzcqVar7 = new zzcq();
        zzcqVar7.zza(4);
        zzh = builder7.withProperty(zzcqVar7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzcq zzcqVar8 = new zzcq();
        zzcqVar8.zza(29);
        zzi = builder8.withProperty(zzcqVar8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzcq zzcqVar9 = new zzcq();
        zzcqVar9.zza(5);
        zzj = builder9.withProperty(zzcqVar9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzcq zzcqVar10 = new zzcq();
        zzcqVar10.zza(59);
        zzk = builder10.withProperty(zzcqVar10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzcq zzcqVar11 = new zzcq();
        zzcqVar11.zza(6);
        zzl = builder11.withProperty(zzcqVar11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzcq zzcqVar12 = new zzcq();
        zzcqVar12.zza(7);
        zzm = builder12.withProperty(zzcqVar12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzcq zzcqVar13 = new zzcq();
        zzcqVar13.zza(58);
        zzn = builder13.withProperty(zzcqVar13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzcq zzcqVar14 = new zzcq();
        zzcqVar14.zza(48);
        zzo = builder14.withProperty(zzcqVar14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzcq zzcqVar15 = new zzcq();
        zzcqVar15.zza(49);
        zzp = builder15.withProperty(zzcqVar15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzcq zzcqVar16 = new zzcq();
        zzcqVar16.zza(18);
        zzq = builder16.withProperty(zzcqVar16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzcq zzcqVar17 = new zzcq();
        zzcqVar17.zza(26);
        zzr = builder17.withProperty(zzcqVar17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzcq zzcqVar18 = new zzcq();
        zzcqVar18.zza(27);
        zzs = builder18.withProperty(zzcqVar18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzcq zzcqVar19 = new zzcq();
        zzcqVar19.zza(28);
        zzt = builder19.withProperty(zzcqVar19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzcq zzcqVar20 = new zzcq();
        zzcqVar20.zza(44);
        zzu = builder20.withProperty(zzcqVar20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzcq zzcqVar21 = new zzcq();
        zzcqVar21.zza(45);
        zzv = builder21.withProperty(zzcqVar21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzcq zzcqVar22 = new zzcq();
        zzcqVar22.zza(19);
        zzw = builder22.withProperty(zzcqVar22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzcq zzcqVar23 = new zzcq();
        zzcqVar23.zza(21);
        zzx = builder23.withProperty(zzcqVar23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzcq zzcqVar24 = new zzcq();
        zzcqVar24.zza(22);
        zzy = builder24.withProperty(zzcqVar24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzcq zzcqVar25 = new zzcq();
        zzcqVar25.zza(8);
        zzz = builder25.withProperty(zzcqVar25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzcq zzcqVar26 = new zzcq();
        zzcqVar26.zza(9);
        zzA = builder26.withProperty(zzcqVar26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzcq zzcqVar27 = new zzcq();
        zzcqVar27.zza(10);
        zzB = builder27.withProperty(zzcqVar27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzcq zzcqVar28 = new zzcq();
        zzcqVar28.zza(11);
        zzC = builder28.withProperty(zzcqVar28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzcq zzcqVar29 = new zzcq();
        zzcqVar29.zza(12);
        zzD = builder29.withProperty(zzcqVar29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzcq zzcqVar30 = new zzcq();
        zzcqVar30.zza(13);
        zzE = builder30.withProperty(zzcqVar30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzcq zzcqVar31 = new zzcq();
        zzcqVar31.zza(14);
        zzF = builder31.withProperty(zzcqVar31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzcq zzcqVar32 = new zzcq();
        zzcqVar32.zza(15);
        zzG = builder32.withProperty(zzcqVar32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzcq zzcqVar33 = new zzcq();
        zzcqVar33.zza(16);
        zzH = builder33.withProperty(zzcqVar33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzcq zzcqVar34 = new zzcq();
        zzcqVar34.zza(17);
        zzI = builder34.withProperty(zzcqVar34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzcq zzcqVar35 = new zzcq();
        zzcqVar35.zza(23);
        zzJ = builder35.withProperty(zzcqVar35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzcq zzcqVar36 = new zzcq();
        zzcqVar36.zza(24);
        zzK = builder36.withProperty(zzcqVar36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzcq zzcqVar37 = new zzcq();
        zzcqVar37.zza(25);
        zzL = builder37.withProperty(zzcqVar37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzcq zzcqVar38 = new zzcq();
        zzcqVar38.zza(39);
        zzM = builder38.withProperty(zzcqVar38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("deleteModelLogEvent");
        zzcq zzcqVar39 = new zzcq();
        zzcqVar39.zza(40);
        zzN = builder39.withProperty(zzcqVar39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzcq zzcqVar40 = new zzcq();
        zzcqVar40.zza(30);
        zzO = builder40.withProperty(zzcqVar40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzcq zzcqVar41 = new zzcq();
        zzcqVar41.zza(31);
        zzP = builder41.withProperty(zzcqVar41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzcq zzcqVar42 = new zzcq();
        zzcqVar42.zza(32);
        zzQ = builder42.withProperty(zzcqVar42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzcq zzcqVar43 = new zzcq();
        zzcqVar43.zza(33);
        zzR = builder43.withProperty(zzcqVar43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzcq zzcqVar44 = new zzcq();
        zzcqVar44.zza(34);
        zzS = builder44.withProperty(zzcqVar44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzcq zzcqVar45 = new zzcq();
        zzcqVar45.zza(35);
        zzT = builder45.withProperty(zzcqVar45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzcq zzcqVar46 = new zzcq();
        zzcqVar46.zza(36);
        zzU = builder46.withProperty(zzcqVar46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzcq zzcqVar47 = new zzcq();
        zzcqVar47.zza(46);
        zzV = builder47.withProperty(zzcqVar47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzcq zzcqVar48 = new zzcq();
        zzcqVar48.zza(47);
        zzW = builder48.withProperty(zzcqVar48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("pipelineAccelerationInferenceEvents");
        zzcq zzcqVar49 = new zzcq();
        zzcqVar49.zza(69);
        zzX = builder49.withProperty(zzcqVar49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzcq zzcqVar50 = new zzcq();
        zzcqVar50.zza(42);
        zzY = builder50.withProperty(zzcqVar50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzcq zzcqVar51 = new zzcq();
        zzcqVar51.zza(50);
        zzZ = builder51.withProperty(zzcqVar51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("leakedHandleEvent");
        zzcq zzcqVar52 = new zzcq();
        zzcqVar52.zza(51);
        zzaa = builder52.withProperty(zzcqVar52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzcq zzcqVar53 = new zzcq();
        zzcqVar53.zza(52);
        zzab = builder53.withProperty(zzcqVar53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzcq zzcqVar54 = new zzcq();
        zzcqVar54.zza(53);
        zzac = builder54.withProperty(zzcqVar54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzcq zzcqVar55 = new zzcq();
        zzcqVar55.zza(54);
        zzad = builder55.withProperty(zzcqVar55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzcq zzcqVar56 = new zzcq();
        zzcqVar56.zza(60);
        zzae = builder56.withProperty(zzcqVar56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzcq zzcqVar57 = new zzcq();
        zzcqVar57.zza(55);
        zzaf = builder57.withProperty(zzcqVar57.zzb()).build();
        FieldDescriptor.Builder builder58 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzcq zzcqVar58 = new zzcq();
        zzcqVar58.zza(56);
        zzag = builder58.withProperty(zzcqVar58.zzb()).build();
        FieldDescriptor.Builder builder59 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzcq zzcqVar59 = new zzcq();
        zzcqVar59.zza(57);
        zzah = builder59.withProperty(zzcqVar59.zzb()).build();
        FieldDescriptor.Builder builder60 = FieldDescriptor.builder("toxicityDetectionCreateEvent");
        zzcq zzcqVar60 = new zzcq();
        zzcqVar60.zza(62);
        zzai = builder60.withProperty(zzcqVar60.zzb()).build();
        FieldDescriptor.Builder builder61 = FieldDescriptor.builder("toxicityDetectionLoadEvent");
        zzcq zzcqVar61 = new zzcq();
        zzcqVar61.zza(63);
        zzaj = builder61.withProperty(zzcqVar61.zzb()).build();
        FieldDescriptor.Builder builder62 = FieldDescriptor.builder("toxicityDetectionInferenceEvent");
        zzcq zzcqVar62 = new zzcq();
        zzcqVar62.zza(64);
        zzak = builder62.withProperty(zzcqVar62.zzb()).build();
        FieldDescriptor.Builder builder63 = FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent");
        zzcq zzcqVar63 = new zzcq();
        zzcqVar63.zza(65);
        zzal = builder63.withProperty(zzcqVar63.zzb()).build();
        FieldDescriptor.Builder builder64 = FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent");
        zzcq zzcqVar64 = new zzcq();
        zzcqVar64.zza(66);
        zzam = builder64.withProperty(zzcqVar64.zzb()).build();
        FieldDescriptor.Builder builder65 = FieldDescriptor.builder("codeScannerScanApiEvent");
        zzcq zzcqVar65 = new zzcq();
        zzcqVar65.zza(67);
        zzan = builder65.withProperty(zzcqVar65.zzb()).build();
        FieldDescriptor.Builder builder66 = FieldDescriptor.builder("codeScannerOptionalModuleEvent");
        zzcq zzcqVar66 = new zzcq();
        zzcqVar66.zza(68);
        zzao = builder66.withProperty(zzcqVar66.zzb()).build();
    }

    private zzgi() {
    }

    @Override // com.google.firebase.encoders.ObjectEncoder, com.google.firebase.encoders.Encoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, ObjectEncoderContext objectEncoderContext) throws IOException {
        zzke zzkeVar = (zzke) obj;
        ObjectEncoderContext objectEncoderContext2 = objectEncoderContext;
        objectEncoderContext2.add(zzb, zzkeVar.zzf());
        objectEncoderContext2.add(zzc, zzkeVar.zzc());
        objectEncoderContext2.add(zzd, (Object) null);
        objectEncoderContext2.add(zze, zzkeVar.zzb());
        objectEncoderContext2.add(zzf, (Object) null);
        objectEncoderContext2.add(zzg, (Object) null);
        objectEncoderContext2.add(zzh, (Object) null);
        objectEncoderContext2.add(zzi, (Object) null);
        objectEncoderContext2.add(zzj, zzkeVar.zzd());
        objectEncoderContext2.add(zzk, zzkeVar.zze());
        objectEncoderContext2.add(zzl, (Object) null);
        objectEncoderContext2.add(zzm, (Object) null);
        objectEncoderContext2.add(zzn, (Object) null);
        objectEncoderContext2.add(zzo, (Object) null);
        objectEncoderContext2.add(zzp, (Object) null);
        objectEncoderContext2.add(zzq, (Object) null);
        objectEncoderContext2.add(zzr, (Object) null);
        objectEncoderContext2.add(zzs, (Object) null);
        objectEncoderContext2.add(zzt, (Object) null);
        objectEncoderContext2.add(zzu, (Object) null);
        objectEncoderContext2.add(zzv, (Object) null);
        objectEncoderContext2.add(zzw, (Object) null);
        objectEncoderContext2.add(zzx, (Object) null);
        objectEncoderContext2.add(zzy, (Object) null);
        objectEncoderContext2.add(zzz, (Object) null);
        objectEncoderContext2.add(zzA, (Object) null);
        objectEncoderContext2.add(zzB, (Object) null);
        objectEncoderContext2.add(zzC, (Object) null);
        objectEncoderContext2.add(zzD, (Object) null);
        objectEncoderContext2.add(zzE, (Object) null);
        objectEncoderContext2.add(zzF, (Object) null);
        objectEncoderContext2.add(zzG, (Object) null);
        objectEncoderContext2.add(zzH, (Object) null);
        objectEncoderContext2.add(zzI, (Object) null);
        objectEncoderContext2.add(zzJ, (Object) null);
        objectEncoderContext2.add(zzK, (Object) null);
        objectEncoderContext2.add(zzL, (Object) null);
        objectEncoderContext2.add(zzM, (Object) null);
        objectEncoderContext2.add(zzN, (Object) null);
        objectEncoderContext2.add(zzO, (Object) null);
        objectEncoderContext2.add(zzP, (Object) null);
        objectEncoderContext2.add(zzQ, zzkeVar.zza());
        objectEncoderContext2.add(zzR, (Object) null);
        objectEncoderContext2.add(zzS, (Object) null);
        objectEncoderContext2.add(zzT, (Object) null);
        objectEncoderContext2.add(zzU, (Object) null);
        objectEncoderContext2.add(zzV, (Object) null);
        objectEncoderContext2.add(zzW, (Object) null);
        objectEncoderContext2.add(zzX, (Object) null);
        objectEncoderContext2.add(zzY, (Object) null);
        objectEncoderContext2.add(zzZ, (Object) null);
        objectEncoderContext2.add(zzaa, (Object) null);
        objectEncoderContext2.add(zzab, (Object) null);
        objectEncoderContext2.add(zzac, (Object) null);
        objectEncoderContext2.add(zzad, (Object) null);
        objectEncoderContext2.add(zzae, (Object) null);
        objectEncoderContext2.add(zzaf, (Object) null);
        objectEncoderContext2.add(zzag, (Object) null);
        objectEncoderContext2.add(zzah, (Object) null);
        objectEncoderContext2.add(zzai, (Object) null);
        objectEncoderContext2.add(zzaj, (Object) null);
        objectEncoderContext2.add(zzak, (Object) null);
        objectEncoderContext2.add(zzal, (Object) null);
        objectEncoderContext2.add(zzam, (Object) null);
        objectEncoderContext2.add(zzan, (Object) null);
        objectEncoderContext2.add(zzao, (Object) null);
    }
}
