package atd.av;

import androidx.exifinterface.media.ExifInterface;
import androidx.room.RoomMasterTable;
import atd.at.o;
/* loaded from: classes.dex */
public interface a {
    public static final o A;
    public static final o B;
    public static final o C;
    public static final o D;
    public static final o E;
    public static final o F;
    public static final o G;
    public static final o H;
    public static final o I;
    public static final o J;
    public static final o K;
    public static final o L;
    public static final o M;
    public static final o N;
    public static final o O;
    public static final o P;
    public static final o Q;
    public static final o R;
    public static final o S;
    public static final o T;
    public static final o U;
    public static final o V;
    public static final o W;
    public static final o X;
    public static final o Y;
    public static final o Z;

    /* renamed from: a  reason: collision with root package name */
    public static final o f12231a;
    public static final o aa;
    public static final o ab;
    public static final o ac;
    public static final o ad;
    public static final o ae;
    public static final o af;
    public static final o ag;
    public static final o ah;
    public static final o ai;
    public static final o b;
    public static final o c;

    /* renamed from: d  reason: collision with root package name */
    public static final o f12232d;
    public static final o e;
    public static final o f;
    public static final o g;
    public static final o h;
    public static final o i;
    public static final o j;
    public static final o k;
    public static final o l;
    public static final o m;
    public static final o n;
    public static final o o;
    public static final o p;
    public static final o q;
    public static final o r;
    public static final o s;
    public static final o t;
    public static final o u;
    public static final o v;
    public static final o w;
    public static final o x;
    public static final o y;
    public static final o z;

    static {
        o oVar = new o("2.16.840.1.101.3.4");
        f12231a = oVar;
        o b2 = oVar.b(ExifInterface.GPS_MEASUREMENT_2D);
        b = b2;
        c = b2.b("1");
        f12232d = b2.b(ExifInterface.GPS_MEASUREMENT_2D);
        e = b2.b(ExifInterface.GPS_MEASUREMENT_3D);
        f = b2.b("4");
        g = b2.b("5");
        h = b2.b("6");
        i = b2.b("7");
        j = b2.b("8");
        k = b2.b("9");
        l = b2.b("10");
        m = b2.b("11");
        n = b2.b("12");
        o = b2.b("13");
        p = b2.b("14");
        q = b2.b("15");
        r = b2.b("16");
        o b3 = oVar.b("1");
        s = b3;
        t = b3.b("1");
        u = b3.b(ExifInterface.GPS_MEASUREMENT_2D);
        v = b3.b(ExifInterface.GPS_MEASUREMENT_3D);
        w = b3.b("4");
        x = b3.b("5");
        y = b3.b("6");
        z = b3.b("7");
        A = b3.b("8");
        B = b3.b("21");
        C = b3.b("22");
        D = b3.b("23");
        E = b3.b("24");
        F = b3.b("25");
        G = b3.b("26");
        H = b3.b("27");
        I = b3.b("28");
        J = b3.b("41");
        K = b3.b(RoomMasterTable.DEFAULT_ID);
        L = b3.b("43");
        M = b3.b("44");
        N = b3.b("45");
        O = b3.b("46");
        P = b3.b("47");
        Q = b3.b("48");
        o b4 = oVar.b(ExifInterface.GPS_MEASUREMENT_3D);
        R = b4;
        S = b4;
        T = b4.b("1");
        U = b4.b(ExifInterface.GPS_MEASUREMENT_2D);
        V = b4.b(ExifInterface.GPS_MEASUREMENT_3D);
        W = b4.b("4");
        X = b4.b("5");
        Y = b4.b("6");
        Z = b4.b("7");
        aa = b4.b("8");
        ab = b4.b("9");
        ac = b4.b("10");
        ad = b4.b("11");
        ae = b4.b("12");
        af = b4.b("13");
        ag = b4.b("14");
        ah = b4.b("15");
        ai = b4.b("16");
    }
}
