package util.dd;

import androidx.exifinterface.media.ExifInterface;
import org.spongycastle.asn1.m;
/* loaded from: classes4.dex */
public interface g {
    public static final m c0;
    public static final m d0;
    public static final m e0;
    public static final m f0;
    public static final m g0;
    public static final m h0;
    public static final m i0;
    public static final m j0;
    public static final m l0;
    public static final m m0;
    public static final m n0;
    public static final m o0;
    public static final m p0;
    public static final m q0;
    public static final m r0;
    public static final m s0;
    public static final m t0;
    public static final m u0;
    public static final m v0;

    static {
        m mVar = new m("1.2.840.10045");
        c0 = mVar;
        m n = mVar.n("1");
        d0 = n;
        e0 = n.n("1");
        m n2 = n.n(ExifInterface.GPS_MEASUREMENT_2D);
        f0 = n2;
        n2.n("3.1");
        g0 = n2.n("3.2");
        h0 = n2.n("3.3");
        m n3 = mVar.n("4");
        i0 = n3;
        n3.n("1");
        m n4 = mVar.n(ExifInterface.GPS_MEASUREMENT_2D);
        j0 = n4;
        l0 = n4.n("1");
        m n5 = n3.n(ExifInterface.GPS_MEASUREMENT_3D);
        m0 = n5;
        n5.n("1");
        n5.n(ExifInterface.GPS_MEASUREMENT_2D);
        n5.n(ExifInterface.GPS_MEASUREMENT_3D);
        n5.n("4");
        m n6 = mVar.n(ExifInterface.GPS_MEASUREMENT_3D);
        n0 = n6;
        m n7 = n6.n("0");
        o0 = n7;
        n7.n("1");
        n7.n(ExifInterface.GPS_MEASUREMENT_2D);
        n7.n(ExifInterface.GPS_MEASUREMENT_3D);
        n7.n("4");
        n7.n("5");
        n7.n("6");
        n7.n("7");
        n7.n("8");
        n7.n("9");
        n7.n("10");
        n7.n("11");
        n7.n("12");
        n7.n("13");
        n7.n("14");
        n7.n("15");
        n7.n("16");
        n7.n("17");
        n7.n("18");
        n7.n("19");
        n7.n("20");
        m n8 = n6.n("1");
        p0 = n8;
        n8.n("1");
        n8.n(ExifInterface.GPS_MEASUREMENT_2D);
        n8.n(ExifInterface.GPS_MEASUREMENT_3D);
        n8.n("4");
        n8.n("5");
        n8.n("6");
        n8.n("7");
        q0 = new m("1.2.840.10040.4.1");
        new m("1.2.840.10040.4.3");
        m mVar2 = new m("1.3.133.16.840.63.0");
        r0 = mVar2;
        mVar2.n(ExifInterface.GPS_MEASUREMENT_2D);
        mVar2.n(ExifInterface.GPS_MEASUREMENT_3D);
        mVar2.n("16");
        m mVar3 = new m("1.2.840.10046");
        s0 = mVar3;
        mVar3.n("2.1");
        m n9 = mVar3.n(ExifInterface.GPS_MEASUREMENT_3D);
        t0 = n9;
        n9.n("1");
        n9.n(ExifInterface.GPS_MEASUREMENT_2D);
        n9.n(ExifInterface.GPS_MEASUREMENT_3D);
        n9.n("4");
        n9.n("5");
        n9.n("6");
        n9.n("7");
        n9.n("8");
        m mVar4 = new m("1.3.133.16.840.9.44");
        u0 = mVar4;
        m n10 = mVar4.n("1");
        v0 = n10;
        n10.n("1");
        n10.n(ExifInterface.GPS_MEASUREMENT_2D);
    }
}
