package com.gemalto.idp.mobile.ui.secureinput;

import com.gemalto.idp.mobile.ui.secureinput.SecureInputBuilder;
/* loaded from: classes2.dex */
public final class SecureInputDefaultSettings {
    public static final int BUTTON_BACKGROUND_COLOR_DISABLED = -1;
    public static final int BUTTON_BACKGROUND_COLOR_NORMAL = -1;
    public static final int BUTTON_BACKGROUND_COLOR_SELECTED = -1894042516;
    public static final int BUTTON_BORDER_COLOR = -1;
    public static final int BUTTON_BORDER_WIDTH = 1;
    public static final int BUTTON_FONT_SIZE = 24;
    public static final boolean BUTTON_PRESS_VISIBILITY = false;
    public static final boolean DEFAULT_IS_DELETE_BUTTON_ALWAYS_ENABLED = false;
    public static final String DEFAULT_KEYS = "1234567890";
    public static final float DEFAULT_OPACITY = 1.0f;
    public static final String DELETE_BUTTON_NAME = "Delete";
    public static final int DELETE_BUTTON_TEXT_COLOR_DISABLED = -1882403636;
    public static final int DELETE_BUTTON_TEXT_COLOR_NORMAL = -2160590;
    public static final int DELETE_BUTTON_TEXT_COLOR_SELECTED = -2160590;
    public static final float DIALOG_HEIGHT_TO_SCREEN_RATIO = 0.6f;
    public static final float DIALOG_WIDTH_TO_SCREEN_RATIO = 0.6f;
    public static final int DISTANCE_BETWEEN_KEY_AND_SUBSCRIPT = 2;
    public static final String FIRST_LABEL = "Enter PIN";
    public static final int INPUT_FIELD_BACKGROUND_COLOR_FOCUS = -208823626;
    public static final int INPUT_FIELD_BACKGROUND_COLOR_UNFOCUS = -1882731045;
    public static final int INPUT_FIELD_COLOR_FOCUS = Integer.MIN_VALUE;
    public static final int INPUT_FIELD_COLOR_UNFOCUS = -2139062144;
    public static final int INPUT_FIELD_FONT_SIZE = 18;
    public static final float KEYPAD_HEIGHT_RATIO = 0.5f;
    public static final int KEY_COLOR_DISABLED = -14994324;
    public static final int KEY_COLOR_NORMAL = -14994324;
    public static final int KEY_COLOR_SELECTED = -14994324;
    public static final int LABEL_COLOR = -14994324;
    public static final int LABEL_FONT_SIZE = 20;
    public static final int LOGO_BAR_BACKGROUND_COLOR = -1;
    public static final int MAXIMUM_INPUT_LENGTH = 19;
    public static final int MAXIMUM_KEYS_LENGTH = 36;
    public static final int MAXIMUM_SUBSCRIPT_LENGTH = 4;
    public static final int MAX_BUTTON_CHARACTER_FONT_SIZE = 100;
    public static final float MAX_OPACITY = 1.0f;
    public static final int MAX_SHIFT_BUTTON_TEXT_LENGTH = 14;
    public static final int MINIMUM_INPUT_LENGTH = 4;
    public static final int MINIMUM_NO_OF_ROWS_WITH_SHIFT_SUPPORT = 2;
    public static final int MIN_BUTTON_CHARACTER_FONT_SIZE = 1;
    public static final float MIN_OPACITY = 0.0f;
    public static final int NO_OF_COLUMNS = 3;
    public static final int NO_OF_ROWS = 4;
    public static final String OK_BUTTON_NAME = "OK";
    public static final int OK_BUTTON_TEXT_COLOR_DISABLED = -1880561432;
    public static final int OK_BUTTON_TEXT_COLOR_NORMAL = -10964904;
    public static final int OK_BUTTON_TEXT_COLOR_SELECTED = -12015288;
    public static final int RIPPLE_EFFECT_COLOR = -487662;
    public static final long RIPPLE_EFFECT_DURATION = 1000;
    public static final int SCREEN_BACKGROUND_COLOR = -1;
    public static final String SECOND_LABEL = "Confirm PIN";
    public static final int SUBSCRIPT_FONT_SIZE = 14;
    public static final SecureInputBuilder.LogoPosition LOGO_IMAGE_POSITION = SecureInputBuilder.LogoPosition.CENTER;
    public static final SecureInputBuilder.OkButtonBehavior DEFAULT_OK_BUTTON_BEHAVIOR = SecureInputBuilder.OkButtonBehavior.AUTOMATICALLY_ENABLED;
    public static final SecureInputBuilder.LabelAlignment LABEL_ALIGNMENT = SecureInputBuilder.LabelAlignment.CENTER;
    public static final SecureInputBuilder.ButtonTouchVisual DEFAULT_BUTTON_VISUAL = SecureInputBuilder.ButtonTouchVisual.HIGHLIGHT;
}
