package com.google.android.gms.internal.mlkit_vision_barcode;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;
/* loaded from: classes2.dex */
final class zzgg implements ObjectEncoder<zzjf> {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzgg zza = new zzgg();
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzcw zzcwVar = new zzcw();
        zzcwVar.zza(1);
        zzb = builder.withProperty(zzcwVar.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzcw zzcwVar2 = new zzcw();
        zzcwVar2.zza(2);
        zzc = builder2.withProperty(zzcwVar2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzcw zzcwVar3 = new zzcw();
        zzcwVar3.zza(37);
        zzd = builder3.withProperty(zzcwVar3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzcw zzcwVar4 = new zzcw();
        zzcwVar4.zza(3);
        zze = builder4.withProperty(zzcwVar4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzcw zzcwVar5 = new zzcw();
        zzcwVar5.zza(20);
        zzf = builder5.withProperty(zzcwVar5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzcw zzcwVar6 = new zzcw();
        zzcwVar6.zza(4);
        zzg = builder6.withProperty(zzcwVar6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzcw zzcwVar7 = new zzcw();
        zzcwVar7.zza(29);
        zzh = builder7.withProperty(zzcwVar7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzcw zzcwVar8 = new zzcw();
        zzcwVar8.zza(5);
        zzi = builder8.withProperty(zzcwVar8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzcw zzcwVar9 = new zzcw();
        zzcwVar9.zza(59);
        zzj = builder9.withProperty(zzcwVar9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzcw zzcwVar10 = new zzcw();
        zzcwVar10.zza(6);
        zzk = builder10.withProperty(zzcwVar10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzcw zzcwVar11 = new zzcw();
        zzcwVar11.zza(7);
        zzl = builder11.withProperty(zzcwVar11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzcw zzcwVar12 = new zzcw();
        zzcwVar12.zza(58);
        zzm = builder12.withProperty(zzcwVar12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzcw zzcwVar13 = new zzcw();
        zzcwVar13.zza(48);
        zzn = builder13.withProperty(zzcwVar13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzcw zzcwVar14 = new zzcw();
        zzcwVar14.zza(49);
        zzo = builder14.withProperty(zzcwVar14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzcw zzcwVar15 = new zzcw();
        zzcwVar15.zza(18);
        zzp = builder15.withProperty(zzcwVar15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzcw zzcwVar16 = new zzcw();
        zzcwVar16.zza(26);
        zzq = builder16.withProperty(zzcwVar16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzcw zzcwVar17 = new zzcw();
        zzcwVar17.zza(27);
        zzr = builder17.withProperty(zzcwVar17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzcw zzcwVar18 = new zzcw();
        zzcwVar18.zza(28);
        zzs = builder18.withProperty(zzcwVar18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzcw zzcwVar19 = new zzcw();
        zzcwVar19.zza(44);
        zzt = builder19.withProperty(zzcwVar19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzcw zzcwVar20 = new zzcw();
        zzcwVar20.zza(45);
        zzu = builder20.withProperty(zzcwVar20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzcw zzcwVar21 = new zzcw();
        zzcwVar21.zza(19);
        zzv = builder21.withProperty(zzcwVar21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzcw zzcwVar22 = new zzcw();
        zzcwVar22.zza(21);
        zzw = builder22.withProperty(zzcwVar22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzcw zzcwVar23 = new zzcw();
        zzcwVar23.zza(22);
        zzx = builder23.withProperty(zzcwVar23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzcw zzcwVar24 = new zzcw();
        zzcwVar24.zza(8);
        zzy = builder24.withProperty(zzcwVar24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzcw zzcwVar25 = new zzcw();
        zzcwVar25.zza(9);
        zzz = builder25.withProperty(zzcwVar25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzcw zzcwVar26 = new zzcw();
        zzcwVar26.zza(10);
        zzA = builder26.withProperty(zzcwVar26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzcw zzcwVar27 = new zzcw();
        zzcwVar27.zza(11);
        zzB = builder27.withProperty(zzcwVar27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzcw zzcwVar28 = new zzcw();
        zzcwVar28.zza(12);
        zzC = builder28.withProperty(zzcwVar28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzcw zzcwVar29 = new zzcw();
        zzcwVar29.zza(13);
        zzD = builder29.withProperty(zzcwVar29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzcw zzcwVar30 = new zzcw();
        zzcwVar30.zza(14);
        zzE = builder30.withProperty(zzcwVar30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzcw zzcwVar31 = new zzcw();
        zzcwVar31.zza(15);
        zzF = builder31.withProperty(zzcwVar31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzcw zzcwVar32 = new zzcw();
        zzcwVar32.zza(16);
        zzG = builder32.withProperty(zzcwVar32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzcw zzcwVar33 = new zzcw();
        zzcwVar33.zza(17);
        zzH = builder33.withProperty(zzcwVar33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzcw zzcwVar34 = new zzcw();
        zzcwVar34.zza(23);
        zzI = builder34.withProperty(zzcwVar34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzcw zzcwVar35 = new zzcw();
        zzcwVar35.zza(24);
        zzJ = builder35.withProperty(zzcwVar35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzcw zzcwVar36 = new zzcw();
        zzcwVar36.zza(25);
        zzK = builder36.withProperty(zzcwVar36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzcw zzcwVar37 = new zzcw();
        zzcwVar37.zza(39);
        zzL = builder37.withProperty(zzcwVar37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("deleteModelLogEvent");
        zzcw zzcwVar38 = new zzcw();
        zzcwVar38.zza(40);
        zzM = builder38.withProperty(zzcwVar38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzcw zzcwVar39 = new zzcw();
        zzcwVar39.zza(30);
        zzN = builder39.withProperty(zzcwVar39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzcw zzcwVar40 = new zzcw();
        zzcwVar40.zza(31);
        zzO = builder40.withProperty(zzcwVar40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzcw zzcwVar41 = new zzcw();
        zzcwVar41.zza(32);
        zzP = builder41.withProperty(zzcwVar41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzcw zzcwVar42 = new zzcw();
        zzcwVar42.zza(33);
        zzQ = builder42.withProperty(zzcwVar42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzcw zzcwVar43 = new zzcw();
        zzcwVar43.zza(34);
        zzR = builder43.withProperty(zzcwVar43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzcw zzcwVar44 = new zzcw();
        zzcwVar44.zza(35);
        zzS = builder44.withProperty(zzcwVar44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzcw zzcwVar45 = new zzcw();
        zzcwVar45.zza(36);
        zzT = builder45.withProperty(zzcwVar45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzcw zzcwVar46 = new zzcw();
        zzcwVar46.zza(46);
        zzU = builder46.withProperty(zzcwVar46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzcw zzcwVar47 = new zzcw();
        zzcwVar47.zza(47);
        zzV = builder47.withProperty(zzcwVar47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzcw zzcwVar48 = new zzcw();
        zzcwVar48.zza(42);
        zzW = builder48.withProperty(zzcwVar48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzcw zzcwVar49 = new zzcw();
        zzcwVar49.zza(50);
        zzX = builder49.withProperty(zzcwVar49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("leakedHandleEvent");
        zzcw zzcwVar50 = new zzcw();
        zzcwVar50.zza(51);
        zzY = builder50.withProperty(zzcwVar50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzcw zzcwVar51 = new zzcw();
        zzcwVar51.zza(52);
        zzZ = builder51.withProperty(zzcwVar51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzcw zzcwVar52 = new zzcw();
        zzcwVar52.zza(53);
        zzaa = builder52.withProperty(zzcwVar52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzcw zzcwVar53 = new zzcw();
        zzcwVar53.zza(54);
        zzab = builder53.withProperty(zzcwVar53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzcw zzcwVar54 = new zzcw();
        zzcwVar54.zza(60);
        zzac = builder54.withProperty(zzcwVar54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzcw zzcwVar55 = new zzcw();
        zzcwVar55.zza(55);
        zzad = builder55.withProperty(zzcwVar55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzcw zzcwVar56 = new zzcw();
        zzcwVar56.zza(56);
        zzae = builder56.withProperty(zzcwVar56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzcw zzcwVar57 = new zzcw();
        zzcwVar57.zza(57);
        zzaf = builder57.withProperty(zzcwVar57.zzb()).build();
    }

    private zzgg() {
    }

    @Override // com.google.firebase.encoders.ObjectEncoder, com.google.firebase.encoders.Encoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, ObjectEncoderContext objectEncoderContext) throws IOException {
        zzjf zzjfVar = (zzjf) obj;
        ObjectEncoderContext objectEncoderContext2 = objectEncoderContext;
        objectEncoderContext2.add(zzb, zzjfVar.zze());
        objectEncoderContext2.add(zzc, zzjfVar.zzb());
        objectEncoderContext2.add(zzd, zzjfVar.zzf());
        objectEncoderContext2.add(zze, (Object) null);
        objectEncoderContext2.add(zzf, (Object) null);
        objectEncoderContext2.add(zzg, (Object) null);
        objectEncoderContext2.add(zzh, (Object) null);
        objectEncoderContext2.add(zzi, (Object) null);
        objectEncoderContext2.add(zzj, (Object) null);
        objectEncoderContext2.add(zzk, (Object) null);
        objectEncoderContext2.add(zzl, zzjfVar.zzc());
        objectEncoderContext2.add(zzm, zzjfVar.zzd());
        objectEncoderContext2.add(zzn, (Object) null);
        objectEncoderContext2.add(zzo, (Object) null);
        objectEncoderContext2.add(zzp, (Object) null);
        objectEncoderContext2.add(zzq, (Object) null);
        objectEncoderContext2.add(zzr, (Object) null);
        objectEncoderContext2.add(zzs, (Object) null);
        objectEncoderContext2.add(zzt, (Object) null);
        objectEncoderContext2.add(zzu, (Object) null);
        objectEncoderContext2.add(zzv, (Object) null);
        objectEncoderContext2.add(zzw, (Object) null);
        objectEncoderContext2.add(zzx, (Object) null);
        objectEncoderContext2.add(zzy, (Object) null);
        objectEncoderContext2.add(zzz, (Object) null);
        objectEncoderContext2.add(zzA, (Object) null);
        objectEncoderContext2.add(zzB, (Object) null);
        objectEncoderContext2.add(zzC, (Object) null);
        objectEncoderContext2.add(zzD, (Object) null);
        objectEncoderContext2.add(zzE, (Object) null);
        objectEncoderContext2.add(zzF, (Object) null);
        objectEncoderContext2.add(zzG, (Object) null);
        objectEncoderContext2.add(zzH, (Object) null);
        objectEncoderContext2.add(zzI, (Object) null);
        objectEncoderContext2.add(zzJ, (Object) null);
        objectEncoderContext2.add(zzK, (Object) null);
        objectEncoderContext2.add(zzL, (Object) null);
        objectEncoderContext2.add(zzM, (Object) null);
        objectEncoderContext2.add(zzN, (Object) null);
        objectEncoderContext2.add(zzO, (Object) null);
        objectEncoderContext2.add(zzP, (Object) null);
        objectEncoderContext2.add(zzQ, zzjfVar.zza());
        objectEncoderContext2.add(zzR, (Object) null);
        objectEncoderContext2.add(zzS, (Object) null);
        objectEncoderContext2.add(zzT, (Object) null);
        objectEncoderContext2.add(zzU, (Object) null);
        objectEncoderContext2.add(zzV, (Object) null);
        objectEncoderContext2.add(zzW, (Object) null);
        objectEncoderContext2.add(zzX, (Object) null);
        objectEncoderContext2.add(zzY, (Object) null);
        objectEncoderContext2.add(zzZ, (Object) null);
        objectEncoderContext2.add(zzaa, (Object) null);
        objectEncoderContext2.add(zzab, (Object) null);
        objectEncoderContext2.add(zzac, (Object) null);
        objectEncoderContext2.add(zzad, (Object) null);
        objectEncoderContext2.add(zzae, (Object) null);
        objectEncoderContext2.add(zzaf, (Object) null);
    }
}
