package atd.ax;

import androidx.exifinterface.media.ExifInterface;
import atd.at.o;
/* loaded from: classes.dex */
public interface a {
    public static final o A;
    public static final o B;
    public static final o C;
    public static final o D;
    public static final o E;
    public static final o F;
    public static final o G;
    public static final o H;
    public static final o I;
    public static final o J;
    public static final o K;
    public static final o L;
    public static final o M;
    public static final o N;
    public static final o O;
    public static final o P;
    public static final o Q;
    public static final o R;
    public static final o S;
    public static final o T;
    public static final o U;
    public static final o V;
    public static final o W;
    public static final o X;
    public static final o Y;
    public static final o Z;

    /* renamed from: a  reason: collision with root package name */
    public static final o f12235a;
    public static final o aA;
    public static final o aB;
    public static final o aC;
    public static final o aD;
    public static final o aE;
    public static final o aF;
    public static final o aG;
    public static final o aH;
    public static final o aI;
    public static final o aJ;
    public static final o aK;
    public static final o aL;
    public static final o aM;
    public static final o aN;
    public static final o aO;
    public static final o aP;
    public static final o aQ;
    public static final o aR;
    public static final o aS;
    public static final o aT;
    public static final o aU;
    public static final o aV;
    public static final o aW;
    public static final o aX;
    public static final o aY;
    public static final o aZ;
    public static final o aa;
    public static final o ab;
    public static final o ac;
    public static final o ad;
    public static final o ae;
    public static final o af;
    public static final o ag;
    public static final o ah;
    public static final o ai;
    public static final o aj;
    public static final o ak;
    public static final o al;
    public static final o am;
    public static final o an;
    public static final o ao;
    public static final o ap;
    public static final o aq;
    public static final o ar;
    public static final o as;
    public static final o at;
    public static final o au;
    public static final o av;
    public static final o aw;
    public static final o ax;
    public static final o ay;
    public static final o az;
    public static final o b;
    public static final o bA;
    public static final o bB;
    public static final o bC;
    public static final o bD;
    public static final o bE;
    public static final o bF;
    public static final o bG;
    public static final o bH;
    public static final o bI;
    public static final o bJ;
    public static final o bK;
    public static final o bL;
    public static final o bM;
    public static final o bN;
    public static final o ba;
    public static final o bb;
    public static final o bc;
    public static final o bd;
    public static final o be;
    public static final o bf;
    public static final o bg;
    public static final o bh;
    public static final o bi;
    public static final o bj;
    public static final o bk;
    public static final o bl;
    public static final o bm;
    public static final o bn;
    public static final o bo;
    public static final o bp;
    public static final o bq;

    /* renamed from: br  reason: collision with root package name */
    public static final o f12236br;
    public static final o bs;
    public static final o bt;
    public static final o bu;
    public static final o bv;
    public static final o bw;
    public static final o bx;
    public static final o by;
    public static final o bz;
    public static final o c;

    /* renamed from: d  reason: collision with root package name */
    public static final o f12237d;
    public static final o e;
    public static final o f;
    public static final o g;
    public static final o h;
    public static final o i;
    public static final o j;
    public static final o k;
    public static final o l;
    public static final o m;
    public static final o n;
    public static final o o;
    public static final o p;
    public static final o q;
    public static final o r;
    public static final o s;
    public static final o t;
    public static final o u;
    public static final o v;
    public static final o w;
    public static final o x;
    public static final o y;
    public static final o z;

    static {
        o oVar = new o("1.2.840.113549.1.1");
        f12235a = oVar;
        b = oVar.b("1");
        c = oVar.b(ExifInterface.GPS_MEASUREMENT_2D);
        f12237d = oVar.b(ExifInterface.GPS_MEASUREMENT_3D);
        e = oVar.b("4");
        f = oVar.b("5");
        g = oVar.b("6");
        h = oVar.b("7");
        i = oVar.b("8");
        j = oVar.b("9");
        k = oVar.b("10");
        l = oVar.b("11");
        m = oVar.b("12");
        n = oVar.b("13");
        o = oVar.b("14");
        p = oVar.b("15");
        q = oVar.b("16");
        o oVar2 = new o("1.2.840.113549.1.3");
        r = oVar2;
        s = oVar2.b("1");
        o oVar3 = new o("1.2.840.113549.1.5");
        t = oVar3;
        u = oVar3.b("1");
        v = oVar3.b("4");
        w = oVar3.b(ExifInterface.GPS_MEASUREMENT_3D);
        x = oVar3.b("6");
        y = oVar3.b("10");
        z = oVar3.b("11");
        A = oVar3.b("13");
        B = oVar3.b("12");
        o oVar4 = new o("1.2.840.113549.3");
        C = oVar4;
        D = oVar4.b("7");
        E = oVar4.b(ExifInterface.GPS_MEASUREMENT_2D);
        F = oVar4.b("4");
        o oVar5 = new o("1.2.840.113549.2");
        G = oVar5;
        H = oVar5.b(ExifInterface.GPS_MEASUREMENT_2D);
        I = oVar5.b("4");
        J = oVar5.b("5");
        K = oVar5.b("7").d();
        L = oVar5.b("8").d();
        M = oVar5.b("9").d();
        N = oVar5.b("10").d();
        O = oVar5.b("11").d();
        P = new o("1.2.840.113549.1.7").d();
        Q = new o("1.2.840.113549.1.7.1").d();
        R = new o("1.2.840.113549.1.7.2").d();
        S = new o("1.2.840.113549.1.7.3").d();
        T = new o("1.2.840.113549.1.7.4").d();
        U = new o("1.2.840.113549.1.7.5").d();
        V = new o("1.2.840.113549.1.7.6").d();
        o oVar6 = new o("1.2.840.113549.1.9");
        W = oVar6;
        X = oVar6.b("1").d();
        Y = oVar6.b(ExifInterface.GPS_MEASUREMENT_2D).d();
        Z = oVar6.b(ExifInterface.GPS_MEASUREMENT_3D).d();
        aa = oVar6.b("4").d();
        ab = oVar6.b("5").d();
        ac = oVar6.b("6").d();
        ad = oVar6.b("7").d();
        ae = oVar6.b("8").d();
        af = oVar6.b("9").d();
        ag = oVar6.b("13").d();
        ah = oVar6.b("14").d();
        ai = oVar6.b("15").d();
        o d2 = oVar6.b("16").d();
        aj = d2;
        ak = oVar6.b("20").d();
        al = oVar6.b("21").d();
        am = oVar6.b("22.1");
        o b2 = oVar6.b("22");
        an = b2;
        ao = b2.b("1").d();
        ap = b2.b(ExifInterface.GPS_MEASUREMENT_2D).d();
        o b3 = oVar6.b("23");
        aq = b3;
        ar = b3.b("1").d();
        as = oVar6.b("52").d();
        at = oVar6.b("15.1");
        au = oVar6.b("15.2");
        av = oVar6.b("15.3");
        o oVar7 = new o("1.2.840.113549.1.9.16.1");
        aw = oVar7;
        ax = oVar7.b(ExifInterface.GPS_MEASUREMENT_2D);
        ay = oVar7.b("4");
        az = oVar7.b("9");
        aA = oVar7.b("23");
        aB = oVar7.b("31");
        o b4 = d2.b(ExifInterface.GPS_MEASUREMENT_3D);
        aC = b4;
        aD = b4.b("9");
        aE = b4.b("14");
        o oVar8 = new o("1.2.840.113549.1.9.16.6");
        aF = oVar8;
        aG = oVar8.b("1");
        aH = oVar8.b(ExifInterface.GPS_MEASUREMENT_2D);
        aI = oVar8.b(ExifInterface.GPS_MEASUREMENT_3D);
        aJ = oVar8.b("4");
        aK = oVar8.b("5");
        aL = oVar8.b("6");
        o oVar9 = new o("1.2.840.113549.1.9.16.2");
        aM = oVar9;
        aN = oVar9.b("1");
        aO = oVar9.b("4");
        aP = oVar9.b("5");
        aQ = oVar9.b("10");
        aR = oVar9.b("11");
        aS = oVar9.b("12");
        aT = oVar9.b("47");
        aU = oVar9.b("7");
        aV = oVar9.b("14");
        o b5 = oVar9.b("15");
        aW = b5;
        o b6 = oVar9.b("16");
        aX = b6;
        o b7 = oVar9.b("17");
        aY = b7;
        aZ = oVar9.b("18");
        o b8 = oVar9.b("19");
        ba = b8;
        bb = oVar9.b("20");
        bc = oVar9.b("21");
        bd = oVar9.b("22");
        be = oVar9.b("23");
        bf = oVar9.b("24");
        bg = oVar9.b("25");
        bh = oVar9.b("26");
        bi = oVar9.b("27");
        bj = oVar9.b("37");
        bk = oVar9.b("38");
        bl = oVar9.b("54");
        bm = oVar9.b("43");
        bn = oVar9.b("40");
        bo = b5;
        bp = b6;
        bq = b7;
        f12236br = b8;
        bs = new o("1.2.840.113549.1.9.16.5.1");
        bt = new o("1.2.840.113549.1.9.16.5.2");
        o oVar10 = new o("1.2.840.113549.1.12");
        bu = oVar10;
        o b9 = oVar10.b("10.1");
        bv = b9;
        bw = b9.b("1");
        bx = b9.b(ExifInterface.GPS_MEASUREMENT_2D);
        by = b9.b(ExifInterface.GPS_MEASUREMENT_3D);
        bz = b9.b("4");
        bA = b9.b("5");
        bB = b9.b("6");
        o b10 = oVar10.b("1");
        bC = b10;
        bD = b10.b("1");
        bE = b10.b(ExifInterface.GPS_MEASUREMENT_2D);
        bF = b10.b(ExifInterface.GPS_MEASUREMENT_3D);
        bG = b10.b("4");
        bH = b10.b("5");
        bI = b10.b("6");
        bJ = b10.b("6");
        bK = new o("1.2.840.113549.1.9.16.3.6");
        bL = new o("1.2.840.113549.1.9.16.3.7");
        bM = new o("1.2.840.113549.1.9.16.3.5");
        bN = new o("1.2.840.113549.1.9.16.3.10");
    }
}
